version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
      
    volumes:
      - .:/usr/src/bull-queue
  redis:
    image: "redis:alpine"

#https://github.com/docker/awesome-compose/blob/master/nginx-nodejs-redis/compose.yaml